---
title: "interactive graph examples"
author: "Marie Bouffard"
date: "10/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here, we'll practice creating some interactive graphs and tables using built-in datasets in R packages.

- Interactive plots: {plotly}
- Interactive tables: {DT}

```{r, include = FALSE}

# Attach packages:

library(tidyverse)
library(plotly)
library(DT)

```

### A. Interactive graph of iris dimensions

Using Edgar Andersen's famous 'iris' dataset
```{r, echo = FALSE}

# use echo = FALSE to make code not show up. Could also apply globally by changing TRUE to FALSE in first (defualt) code chunk

iris_graph <- ggplot(data = iris, aes(x = Petal.Width, y = Petal.Length)) +
  geom_point(aes(size = Sepal.Width,
                 color = Species),
             alpha = 0.5) +
  theme_minimal() +
  labs(title = "My iris graph", 
       x = "Petal width (cm)", 
       y = "Petal length (cm)")

# iris_graph
# Comment show graph out so it doesn't show up in html
# If you want to comment out an entire code chunk add eval = FALSE to squiggly bracket heading of code chunk 

ggplotly(iris_graph)

# Use cntrl. a + space to stage all files in Git tab

```

### Make an interactive table with DT
```{r}

datatable(msleep)

```


